export const actionTypes = {
  GET_USER: 'GET_USER',
  VALIDATE_USER: ' VALIDATE_USER',
  VALIDATE_USER_FAILED: 'VALIDATE_USER_FAILED',
  VALIDATE_TOKEN_SUCCESS: 'VALIDATE_TOKEN_SUCCESS',
  VALIDATE_TOKEN_FAILED: 'VALIDATE_TOKEN_FAILED',
  START_RUN: 'START_RUN',
  STOP_RUN: 'STOP_RUN',
  RUN_DATA: 'RUN_DATA',
  SEND_POST: 'SEND_POST',
  SEND_POST_FAILED: 'SEND_POST_FAILED',
  FOLLOW_USER: 'FOLLOW_USER',
  FOLLOW_USER_FAILED: 'FOLLOW_USER_FAILED',
  UNFOLLOW_USER: 'UNFOLLOW_USER',
  UNFOLLOW_USER_FAILED: 'UNFOLLOW_USER_FAILED'
}